# Site settings
title: fast.ai
repository: fastai/dlcert1
email: info@fast.ai
description: > # this means to ignore newlines until "baseurl:"
  fast.ai's deep learning MOOC. The start of an exciting journey into deep
  neural networks!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://course.fast.ai" # the base hostname & protocol for your site
twitter_username: fastdotai
github_username:  fastai

# Build settings
markdown: kramdown

paginate: 4
paginate_path: "blog/page:num"
